"""Link doctors to users

Revision ID: 0b259585d2d0
Revises: 594c2be47673
Create Date: 2026-09-03 19:17:18.560422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b259585d2d0'
down_revision = '594c2be47673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staffs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'staffs', ['user_id'])
    op.create_foreign_key(None, 'staffs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staffs', type_='foreignkey')
    op.drop_constraint(None, 'staffs', type_='unique')
    op.drop_column('staffs', 'user_id')
    # ### end Alembic commands ###
