"""Add appointment time

Revision ID: 307a5095ebef
Revises: 560f51b69ced
Create Date: 2026-09-09 21:09:43.224084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307a5095ebef'
down_revision = '560f51b69ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('appointment_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'appointment_time')
    # ### end Alembic commands ###
