"""Link patients to users

Revision ID: 594c2be47673
Revises: cb3872b7888a
Create Date: 2026-09-03 19:12:30.783392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594c2be47673'
down_revision = 'cb3872b7888a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'patients', ['user_id'])
    op.create_foreign_key(None, 'patients', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_column('patients', 'user_id')
    # ### end Alembic commands ###
