"""Add appointment status

Revision ID: cb3872b7888a
Revises: dd796e12aad4
Create Date: 2026-09-03 18:59:21.054816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb3872b7888a'
down_revision = 'dd796e12aad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'appointments',
    sa.Column('status', sa.String(), nullable=False, server_default='Pending')
)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'status')
    # ### end Alembic commands ###
